linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (bytes.Buffer).WriteByte

run:
  timeout: 3m
