apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-proxy.fullname" . }}
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pg
      protocol: TCP
      name: pg
  selector:
    {{- include "db-proxy.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-proxy.fullname" . }}-metrics
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "db-proxy.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.adminService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-proxy.fullname" . }}-admin
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.adminService.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "db-proxy.selectorLabels" . | nindent 4 }}
{{- end }}
